"""document versioning - superseded_by_id

Revision ID: 36b658b82dd4
Revises: c744ece0db7c
Create Date: 2026-10-01 00:03:09.270680

Superseded-but-kept document versioning: when a customer re-uploads a
document of the same type for the same application (e.g. responding to a
CUSTOMER_ACTION_REQUIRED request), the old row is kept and pointed at its
replacement via this self-referencing, nullable FK - never deleted or
overwritten. NULL means "current". See app/services/documents.py's
_supersede_prior_versions(). Purely additive - no data backfill needed,
existing rows simply start out as "current" (NULL).
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b658b82dd4'
down_revision = 'c744ece0db7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superseded_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_superseded_by_id'), ['superseded_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'documents', ['superseded_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_superseded_by_id'))
        batch_op.drop_column('superseded_by_id')

    # ### end Alembic commands ###
