"""prime workflow revision - phase 1 and 2: additive schema

Revision ID: 627a6b23d180
Revises: 3ec191c6a228
Create Date: 2026-09-30 00:47:35.074312

Purely additive - new tables, new nullable columns, and one new enum value
(document_type.proof_of_income). No existing column's enum VALUE SET
changes here - that's the separate, higher-risk c744ece0db7c migration that
follows this one (see its docstring for why it's split out).

Hand-edited after `flask db migrate` autogenerated the bulk of this: two
enum-typed columns (loan_applications.purpose_category, loans.closure_reason)
use brand-new Postgres enum types that autogenerate's `add_column` does NOT
create automatically - see the "type does not exist" bug this project's
prior migration (3ec191c6a228) shipped with. `disbursement_method` doesn't
need the same fix here because `create_table('disbursements', ...)` below
(which DOES auto-create enum types) runs first in this same migration and
creates it before `loan_applications.disbursement_method_requested`'s
add_column reuses it.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '627a6b23d180'
down_revision = '3ec191c6a228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_application_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('relationship_to_applicant', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=32), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referees_loan_application_id'), ['loan_application_id'], unique=False)

    op.create_table('terms_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_application_id'], ['loan_applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms_acceptances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_acceptances_loan_application_id'), ['loan_application_id'], unique=True)

    op.create_table('disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('bsp_mobile_banking', 'cash_on_hand', name='disbursement_method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method_reference', sa.String(length=255), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disbursements_loan_id'), ['loan_id'], unique=True)

    # add_column() does not auto-create a brand-new Postgres ENUM type
    # (unlike create_table()) - create it explicitly first. No-op on SQLite.
    sa.Enum(
        'business', 'school_fees', 'medical', 'home_improvement',
        'debt_consolidation', 'other', name='loan_purpose_category',
    ).create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose_category', sa.Enum('business', 'school_fees', 'medical', 'home_improvement', 'debt_consolidation', 'other', name='loan_purpose_category'), nullable=True))
        batch_op.add_column(sa.Column('confirmed_full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirmed_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirmed_phone_number', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('prime_category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('disbursement_method_requested', sa.Enum('bsp_mobile_banking', 'cash_on_hand', name='disbursement_method'), nullable=True))
        batch_op.add_column(sa.Column('disbursement_account_reference', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('action_required_note', sa.String(length=1000), nullable=True))
        batch_op.alter_column('term_months',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('repayment_frequency',
               existing_type=postgresql.ENUM('weekly', 'biweekly', 'monthly', name='repayment_frequency'),
               nullable=True,
               existing_server_default=sa.text("'monthly'::repayment_frequency"))

    sa.Enum('paid_in_full', 'defaulted', name='loan_closure_reason').create(
        op.get_bind(), checkfirst=True
    )

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('closure_reason', sa.Enum('paid_in_full', 'defaulted', name='loan_closure_reason'), nullable=True))
        batch_op.alter_column('term_months',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

    # New DocumentType member - purely additive (no existing values change),
    # so no need for the value-swap pattern the next migration uses. Native
    # Postgres enums can't add a value mid-transaction on very old server
    # versions, but modern Postgres (Supabase) allows it as long as the new
    # value isn't *used* within this same transaction, which it isn't here.
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("ALTER TYPE document_type ADD VALUE IF NOT EXISTS 'proof_of_income'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_column('reported_at')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('term_months',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('closure_reason')
        batch_op.drop_column('term_days')

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.alter_column('repayment_frequency',
               existing_type=postgresql.ENUM('weekly', 'biweekly', 'monthly', name='repayment_frequency'),
               nullable=False,
               existing_server_default=sa.text("'monthly'::repayment_frequency"))
        batch_op.alter_column('term_months',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('action_required_note')
        batch_op.drop_column('disbursement_account_reference')
        batch_op.drop_column('disbursement_method_requested')
        batch_op.drop_column('prime_category')
        batch_op.drop_column('confirmed_phone_number')
        batch_op.drop_column('confirmed_email')
        batch_op.drop_column('confirmed_full_name')
        batch_op.drop_column('purpose_category')

    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disbursements_loan_id'))

    op.drop_table('disbursements')
    with op.batch_alter_table('terms_acceptances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_acceptances_loan_application_id'))

    op.drop_table('terms_acceptances')
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referees_loan_application_id'))

    op.drop_table('referees')
    # ### end Alembic commands ###

    # Native Postgres ENUM types are auto-created on upgrade but NOT
    # auto-dropped by drop_table()/drop_column() - drop them explicitly so a
    # downgrade -> upgrade cycle doesn't collide with an existing type.
    # (document_type.proof_of_income is NOT reverted here: Postgres has no
    # "DROP VALUE" for enums, only a full type rebuild. Since document_type
    # already had rows using pre-existing values before this migration and
    # could plausibly gain proof_of_income-tagged rows after it, silently
    # rebuilding the type on downgrade risks orphaning that data - left
    # as a manual follow-up if a downgrade past this migration is ever needed.)
    if op.get_bind().dialect.name == 'postgresql':
        for enum_name in ('disbursement_method', 'loan_purpose_category', 'loan_closure_reason'):
            sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
