"""payment receipts and reporting fields

Revision ID: 67a24cb3ec63
Revises: 36b658b82dd4
Create Date: 2026-10-01 00:24:53.196654

Adds payment_date (NOT NULL, no default - the customer/officer always
supplies it, see payment_processing.record_payment()'s "defaults to today"
Python-side fallback), reference_number, and rejection_reason to
payment_transactions; documents.payment_transaction_id for receipt uploads.

payment_date is safe to add as NOT NULL with no backfill here because
payment_transactions has zero existing rows in every environment this has
been run against so far (confirmed before running - see the Phase 3 report).
If this is ever run against a database that already has payment rows,
backfill payment_date (e.g. from reported_at::date) before this migration,
or add it nullable-first and tighten in a follow-up.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a24cb3ec63'
down_revision = '36b658b82dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_payment_transaction_id'), ['payment_transaction_id'], unique=False)
        batch_op.create_foreign_key(None, 'payment_transactions', ['payment_transaction_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('payment_date')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_payment_transaction_id'))
        batch_op.drop_column('payment_transaction_id')

    # ### end Alembic commands ###
